### PR TITLE
Make enableXtal overridable to avoid 2-second delay when crystal not …

### PR DESCRIPTION
**Pull request by barawn**
…present.

### CODE REVIEW

**Comment by RickKimball** [comment]
I think the attribute is supposed to be on the declaration in the header file, not on the definition in the .cpp file

**Comment by barawn** [comment]
It does actually work like this, because wiring.c is what actually contains the object to link to - other object files don't need to know the reference is weak because they're just trying to link to something.

But I changed it to duplicate the way that it's done in HardwareSerial.h/.cpp, although I left off the extern declaration because declaring a function prototype external is completely redundant.

**Comment by RickKimball** [comment]
@barawn I realize you had it correct the first time. 

Energia.h:
extern "C" void enableXtal(void);

wiring.c
void  __attribute__((weak)) enableXtal(void);

void enableXtal(void) {
... all the code ...
}

I did test the code and realized for the smaller G series chips, the enableXtal() function is being called twice. I'm pretty sure this wasn't the intent.  This function is a ifdefed to death.

**Comment by barawn** [comment]
Ha! That's actually issue #10 . It was fixed by this commit [https://github.com/energia/Energia/commit/49422e4d88b829531c4d33aef23faa865ed897ac](url) in the old Energia tree, but didn't get propagated in.

**Comment by barawn** [comment]
issue #10 should be fixed again here. I also changed the declaration to match your suggestion, except the extern "C" isn't required because it's already in an extern "C" block, and you really need the __attribute__ (rather than just attribute).

**Pull request merged**
