### PR TITLE
New compiler

### PR DESCRIPTION
**Pull request by StefanSch**
This updates allow to also use the new generation of the msp gcc compiler
It also includes some improvements for maintenance and future Launchpad additions.

### CODE REVIEW

**Comment by rei-vilo** [comment]
Could you be add the macro for `FRAM` included in the pull-request #31?

**Comment by RickKimball** [comment]
Is there going to be a build menu item to switch between msp430-gcc and msp430-elf-gcc?

**Comment by RickKimball** [comment]
Is there a reason to use the -O2 optimization flag instead of -Os?  Why is -lstdc++ included for libraries

**Comment by rei-vilo** [comment]
Wasn't `-O2` bugged?

**Comment by RickKimball** [comment]
I'm not sure what that means rei-vilo

**Comment by RickKimball** [comment]
I noticed that CCS is shipping with msp430-elf-gcc with a gcc 6 version. Is there a reason that CCS and Energia aren't using the same versions? Wouldn't that make it easier to use energia projects in CCS?

**Comment by rei-vilo** [comment]
@RickKimball Sorry! 

The `-O` parameter sets the optimisation level. Some levels, here `-O2`, may be bugged while others, like `-Os`, still work fine with the new compiler.

**Comment by RickKimball** [comment]
So you agree that it probably shouldn't be using -O2?

**Comment by rei-vilo** [comment]
There is no secret, only the trial and error approach can provide an answer, unless the GCC provides all the documentation on the bugs.

See for example https://forum.pjrc.com/threads/40829-Toolchain-update-will-need-help-testing and https://forum.pjrc.com/threads/41568-Teensyduino-1-36-Beta-1-(ARM-Toolchain-Update) for GCC agains another platform.

**Comment by RickKimball** [comment]
You can't look at other gcc compilers to make decisions about msp430-elf-gcc. Its problems are unique to itself.

**Comment by RickKimball** [comment]
Why is dtostrf() using sprintf() stdlib functions? This is going to inflate the size of both the flash and ram.

**Comment by rei-vilo** [comment]
> You can't look at other gcc compilers to make decisions about msp430-elf-gcc. Its problems are unique to itself.

I provided the links just for example. Changing a compiler is a huge operation.

**Comment by RickKimball** [comment]
Has any of this been compiled with the compiler warnings on? I see many discouraging compiler warnings with using the msp430g2553.

**Comment by RickKimball** [comment]
The reported size of the Sketch is incorrect for any cpu that is placing its code in upper memory. I compiled the ASCIITable.ino it reported:
```
Sketch uses 1,218 bytes (2%) of program storage space. Maximum is 48,128 bytes.
Global variables use 198 bytes (2%) of dynamic memory, leaving 7,994 bytes for local variables. Maximum is 8,192 bytes.
```
If you use the size command with no args it adds up all the text and rodata sections, not just the lower memory ones.
```
$ msp430-elf-size  ASCIITable.ino.elf
   text	   data	    bss	    dec	    hex	filename
   4646	    102	    196	   4944	   1350	ASCIITable.ino.elf
$ 
```
The missing bytes are in the .upper.text section and .rodata2

**Comment by RickKimball** [comment]
The linker grouping command line arguments are completely neutered based on where they are used in platform.txt. They should be wrapping all the sketches objects and the core library file. They aren't

-Wl,--start-group *... there is nothing being wrapped ... * -Wl,--end-group ...

should be something like:

 -Wl,--start-group {object_files} "{build.path}/{archive_file}" -Wl,--end-group

**Comment by RickKimball** [comment]
Maxium flash size is wrong for boards that are using upper addresses as .text.  MSP430F5529 says it only has 48128 bytes, it isn't 128k but it isn't 48128.

Also, is the expectation that users will force code into lower memory themselves on these large flash sized chips?

**Comment by robertinant** [comment]
@RickKimball what do you suggest we use in dtostrf()? I would be happy to get rid of sprintf().

**Comment by RickKimball** [comment]
Why is this pull in here? Shouldn't this be part of the msp430-ng-core?

**Pull request merged**
